export const attributeMap = {
  //map react props to dom attributes
  'className': 'class',
  'htmlFor': 'for',
  'value': 'value',
  'checked': 'checked',
  'disabled': 'disabled',
  'readOnly': 'readonly',
  'src': 'src',
  'href': 'href',
  'type': 'type',
  'placeholder': 'placeholder',
  'name': 'name',
  'id': 'id',
  'style': 'style',
  'title': 'title',
  'alt': 'alt',
  'width': 'width',
  'height': 'height',
  'colspan': 'colspan',
  'rowspan': 'rowspan',
  'colspan': 'colspan',
  'rowspan': 'rowspan',
  'checked': 'checked',
  'disabled': 'disabled',
  'readOnly': 'readonly',

  //map react props to dom events
  'onClick': 'click',
  'onChange': 'change',
  'onSubmit': 'submit',
  'onFocus': 'focus', 'onBlur': 'blur',
  'onMouseOver': 'mouseover', 'onMouseOut': 'mouseout',
  'onMouseEnter': 'mouseenter', 'onMouseLeave': 'mouseleave',
  'onKeyDown': 'keydown', 'onKeyUp': 'keyup',
  'onKeyPress': 'keypress',
  'onDoubleClick': 'dblclick',
  'onWheel': 'wheel',
  'onScroll': 'scroll',
  'onCopy': 'copy',
  'onCut': 'cut',
  'onPaste': 'paste',
  'onDrag': 'drag',
  'onDragEnd': 'dragend',
  'onDragEnter': 'dragenter',
  'onDragExit': 'dragexit',
  'onDragLeave': 'dragleave',
  'onDragOver': 'dragover',
  'onDragStart': 'dragstart',
  'onDrop': 'drop',
  'onSelect': 'select',
  'onTouchCancel': 'touchcancel',
  'onTouchEnd': 'touchend',
  'onTouchMove': 'touchmove',
  'onTouchStart': 'touchstart',

}